### ISSUE TITLE
display not updating

### ISSUE THREAD

**Issue by osborne82** [bruxy70/Home-Assistant-ESPHome-Weather-Station#2]
hi fairly new to the nextion display so unsure if iv done this correctly 
flashed d1 mini with the weather yamel no problems 
loaded the hmi file into the latest  Nextion Editor and exported a .tfi file which i then flash onto the display again all good so far 
now hook up the rx tx and power everything boots up and display powers up but the sensors dont get populated and doesnt flick between the two pages. only thing i can do is press the plus n minus buttons on the screen for brightness. 
i added the example sensors to my configuration.yamel they show up in home assistant 

i feel iv probably missed something obvious :) but stuck 
thanks

**Comment by bruxy70** [comment]
Hi. I think that means that the d1 mini and display do not communicate. I'd check if the RX and TX are not swapped (RX on d1 mini should go to TX on the display and vice versa), and that the pin IDs are set correctly. You can then make a simple test - e.g. in the lambda do simply it.set_component_text("inside","TEST"); to see if the communication works - this does not use any sensor data, but static text - once you get that working you can get back to the origina configuration.

**Comment by osborne82** [comment]
Thanks played around some more swapping the tx n rx still nothing. I then
used a different display and bingo most of it started working. Although
temperature is saying NAN the second page does infact show time etc.
I'll keep playing but thank you for your time and the project :)
