### ISSUE TITLE
HMI file issues

### ISSUE THREAD

**Issue by simonjowett** [bruxy70/Home-Assistant-ESPHome-Weather-Station#6]
I downloaded the HMI file but on trying to open it in the Nextion editor I get an error message and the file fails to open.
"Wrong resource file or resource file has been damaged"

**Comment by bruxy70** [comment]
Not sure why this is. It opens fine here. Could be a different version of the editor? Happened to me in the past, they do not make them backward compatible.

**Comment by simonjowett** [comment]
Issue is resolved.  It seems to be a bit of strange behavior of the software somehow.  When I click for the HMI file to download I'm presented by a pop-up window asking me if I want to "Open" or "Save" the file.  If I choose 'open' then it fails, if I choose 'save' (and then browse to open the file inside the Nextion editor), it works fine.  My platform is windows 10 laptop.
