### ISSUE TITLE
[Question] temperature icons

### ISSUE THREAD

**Issue by pniewiadowski** [bruxy70/Home-Assistant-ESPHome-Weather-Station#7]
Hi Vaclav,

first of all thank you very much for this project. I made one for me too, and I used the 3d print model - fits perfectly.

But since, I don't have a pool I would like to put there other measurement and here is the question: from where you took the icons?
I would like to find one with similar look for the other measurement (it will be humidity actually).

PS. I am watching your YT videos. Keep it up!
Greetings from Poland.

**Comment by bruxy70** [comment]
Hi,
I made them in Inkscape, based on some template. So I am afraid you won't find their siblings.
Greetings to Poland :).

**Comment by pniewiadowski** [comment]
I found it.
If anybody will be looking for some of the icons in the same style, you can find it here:
https://www.visualpharm.com/free-icons/temperature%20inside-595b40b85ba036ed117db483
