### ISSUE TITLE
sun_elevation feature

### ISSUE THREAD

**Issue by pniewiadowski** [bruxy70/Home-Assistant-ESPHome-Weather-Station#8]
Trying to fit your code with my needs I found this:

` if (id(sun_elevation)>0) {`

It seems it doesn't work for me unless I add here:

` if (id(sun_elevation).state>0) {`

PS. Finally I replaced this with the Xiaomi illuminance value, which I find more suited for this functionality.

**Comment by bruxy70** [comment]
Oh, thanks! Fixed!
