### ISSUE TITLE
Display don´t show any values

### ISSUE THREAD

**Issue by Mikro007** [bruxy70/Home-Assistant-ESPHome-Weather-Station#9]
Hi!
I followed your guide 100% but I dont get the display to show values from sensors, it just shows the first picture and not changes pictures eather. 

What do I wrong?

**Comment by bruxy70** [comment]
Hard to say. Probably the board does not communicate with the display. My recommendation is to study ESPHome, experiment, have fun with it, be patient, take it easy. You have to configure the serial configuration, the correct GPIO ports, make sure you connect RX to TX and TX to RX. That the speed is configured  correctly. Start from basics, try to set static values (constants, static text or number). Once this works connect that back to HA API.

**Comment by Mikro007** [comment]
It was just wrong connection with TX/RX. TX from display will go to RX on Wemos. RX from display will go to TX on Wemos.
When display is black, wait for it to respond again to get the values.
